name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        php-versions: ['7.3', '7.4', '8.0']
    name: PHP ${{ matrix.php-versions }} Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
    - name: phpize
      run: phpize  
    - name: configure
      run: ./configure --enable-di
    - name: make
      run: make
    - name: test
      run: php -n -d extension_dir=modules/ -d extension=di.so run-tests.php -P .
